---
functional:
  - Пользователь должен иметь возможность создавать свою игру. 
  - Пользователь должен иметь возможность заходить в лобби, которые создали другие игроки. 
  - Пользователь должен иметь возможность играть с ботами и реальными игроками. 
  - Сайт должен иметь глобальный чат. 
  - Пользователь должен иметь возможность просматривать недельный/месячный/глобальный лидерборд. 
  - Пользователь должен иметь возможность просматривать записи и результаты прошедших состязаний.  
  - Пользователь должен иметь возможность просматривать игроков, которые онлайн на текущий момент. 
  - Пользователь должен иметь возможность принимать участие в турнирах. 
  - Пользовател должен иметь возможность создавать турниры самостоятельно. 
  - Пользователь должент иметь возможность настраивать турнир, который он создает. 
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть совместимым с последними версиями бразуеров 
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен поддерживать как минимум два языка (RUS/ENG)
  - Сайт должен корректно отображаться на мобильных устройствах
implicit:
  - Сайт должен соотвествовать стандарту GDPR
